import type { HistoricalRfpRecord } from "@/types/historical";

export const HISTORICAL_RFPS: HistoricalRfpRecord[] = [
  {
    id: "hist-pepsi-mlb-2025",
    createdAt: "2025-03-10T09:00:00Z",
    updatedAt: "2025-04-22T16:00:00Z",
    completedAt: "2025-04-22T16:00:00Z",
    outcome: "Won",
    tags: ["MLB", "brand lift", "PMP", "Fan Graph", "programmatic video"],
    summary:
      "Pepsi MLB season awareness with brand lift study across baseball fan segments. Won with Fan Graph audiences and moment-based video on DV360.",
    advertiser: "Pepsi",
    agency: "Omnicom",
    campaign: "MLB Thirst Trap Season",
    owner: "Sarah Chen",
    deadline: "2025-03-28",
    status: "Complete",
    complexity: "Medium",
    riskLevel: "Low",
    percentComplete: 100,
    intakeNotes:
      "Pepsi launching MLB season campaign. Need baseball fan audiences 18-34, brand lift study, programmatic video on PMP. Budget $3.2M. Home run and strikeout moments.",
    solutionBrief: {
      opportunity: {
        advertiser: "Pepsi",
        agency: "Omnicom",
        campaign: "MLB Thirst Trap Season",
        owner: "Sarah Chen",
      },
      timing: { flight: "Apr 1 – Oct 1, 2025", deadline: "2025-03-28" },
      business: {
        objective: "Drive brand awareness and consideration during MLB season",
        kpi: "Reach, VCR, brand lift (+4pts)",
        budget: "$3.2M",
      },
      audience: {
        target: "Baseball fans 18-34, sports viewers, soda category intenders",
        markets: "US — top 25 MLB markets",
        exclusions: "Competitive beverage purchasers (30d)",
      },
      activation: {
        channels: "Programmatic video, CTV, display",
        pmp: "Yes — Genius Sports MLB PMP on DV360",
        dsp: "DV360",
        sponsorshipNeeds: "None",
        momentsTriggers: "Home run, strikeout, inning break",
      },
      measurement: {
        attribution: "Multi-touch attribution",
        liftStudy: "Required — brand lift study",
        reporting: "Weekly dashboards + postseason readout",
        enrichment: "Fan Graph baseball affinity segments",
      },
      recommendedProducts: [
        "Curated Deals",
        "Audiences / Fan Graph",
        "Moments",
        "Measurement / Insights",
      ],
    },
    workstreams: [],
    risks: [],
    proposalDraft: {
      executiveSummary:
        "Pepsi sought MLB season awareness with measurable brand impact. Genius Sports delivered a moment-driven video strategy with Fan Graph baseball audiences and a brand lift study.",
      strategicRecommendation:
        "Activate around high-engagement baseball moments with Pepsi-branded video tied to home runs and strikeouts.",
      audienceStrategy:
        "Target Baseball Superfans and Sports Viewers via Fan Graph. Weight top 25 MLB markets by team affinity.",
      recommendedProducts:
        "Curated Deals, Audiences / Fan Graph, Moments, Measurement / Insights",
      activationPlan:
        "Apr–Oct flight on DV360 PMP. Home run and strikeout moment triggers with DCO-ready assets.",
      measurementPlan:
        "Brand lift study (+4pt target) with multi-touch attribution. Weekly Fan Graph enrichment reporting.",
      openQuestions: "None — campaign delivered on schedule.",
      internalCaveats: "Final proposal delivered and accepted by client.",
    },
    currentStage: "Complete",
    nextAction: "Archive — won and delivered",
  },
  {
    id: "hist-draftkings-nba-2025",
    createdAt: "2024-11-05T10:00:00Z",
    updatedAt: "2025-01-15T14:00:00Z",
    completedAt: "2025-01-15T14:00:00Z",
    outcome: "Won",
    tags: ["NBA", "gambling", "moments", "legal review", "live odds"],
    summary:
      "DraftKings NBA live odds awareness with moment triggers and state-level compliance. Won after legal review and responsible gaming messaging.",
    advertiser: "DraftKings",
    agency: "WPP",
    campaign: "NBA Live Odds Push",
    owner: "Mike Torres",
    deadline: "2024-11-22",
    status: "Complete",
    complexity: "High",
    riskLevel: "Medium",
    percentComplete: 100,
    intakeNotes:
      "DraftKings NBA season push for live odds features. Gambling category — legal review required. NBA fan targeting 21+, moment triggers around buzzer beaters and overtime.",
    solutionBrief: {
      opportunity: {
        advertiser: "DraftKings",
        agency: "WPP",
        campaign: "NBA Live Odds Push",
        owner: "Mike Torres",
      },
      timing: { flight: "Jan 15 – Jun 15, 2025", deadline: "2024-11-22" },
      business: {
        objective: "Drive awareness of live in-game odds during NBA season",
        kpi: "Reach, odds page visits, app installs",
        budget: "$2.1M",
      },
      audience: {
        target: "NBA fans 21+, sports bettors, fantasy players",
        markets: "US — legal betting states only",
        exclusions: "Under 21, non-legal states",
      },
      activation: {
        channels: "Programmatic display, video, in-app",
        pmp: "Yes",
        dsp: "The Trade Desk",
        sponsorshipNeeds: "None",
        momentsTriggers: "Buzzer beater, overtime start, 4th quarter",
      },
      measurement: {
        attribution: "Last-click + view-through",
        liftStudy: "Not requested",
        reporting: "Weekly reach/frequency + odds engagement",
        enrichment: "State-level compliance tagging",
      },
      recommendedProducts: ["Curated Deals", "Moments", "Measurement / Insights"],
    },
    workstreams: [],
    risks: [],
    proposalDraft: {
      executiveSummary:
        "DraftKings needed NBA season awareness for live odds in a regulated category. Genius Sports delivered compliant moment-based activation with responsible gaming guardrails.",
      strategicRecommendation:
        "Maximize reach during high-intent NBA moments while maintaining strict age and geo compliance.",
      audienceStrategy: "NBA fans 21+ in approved states with fantasy player overlap.",
      recommendedProducts: "Curated Deals, Moments, Measurement / Insights",
      activationPlan:
        "Jan–Jun flight on TTD. Buzzer beater and overtime moment triggers with RG messaging.",
      measurementPlan: "Last-click + VTA. Weekly state-level compliance reporting.",
      openQuestions: "None.",
      internalCaveats: "Legal review completed before client delivery.",
    },
    currentStage: "Complete",
    nextAction: "Archive — won and delivered",
  },
  {
    id: "hist-verizon-nfl-2024",
    createdAt: "2024-06-01T08:00:00Z",
    updatedAt: "2024-07-18T11:00:00Z",
    completedAt: "2024-07-18T11:00:00Z",
    outcome: "Lost",
    tags: ["NFL", "sponsorship", "broadcast", "managed service", "5G"],
    summary:
      "Verizon NFL 5G sponsorship integration with broadcast and digital amplification. Lost to competitor on broadcast package pricing.",
    advertiser: "Verizon",
    agency: "Horizon",
    campaign: "NFL 5G Network Showcase",
    owner: "Lisa Park",
    deadline: "2024-06-20",
    status: "Complete",
    complexity: "High",
    riskLevel: "Medium",
    percentComplete: 100,
    intakeNotes:
      "Verizon extending NFL partnership with 5G network showcase. Broadcast integration, managed service, $5M budget. Sponsorship recall and network quality perception KPIs.",
    solutionBrief: {
      opportunity: {
        advertiser: "Verizon",
        agency: "Horizon",
        campaign: "NFL 5G Network Showcase",
        owner: "Lisa Park",
      },
      timing: { flight: "Sep 5, 2024 – Feb 9, 2025", deadline: "2024-06-20" },
      business: {
        objective: "Showcase Verizon 5G network quality through NFL sponsorship",
        kpi: "Sponsorship recall, brand lift, network quality perception",
        budget: "$5M",
      },
      audience: {
        target: "NFL fans 25-54, Verizon intenders, tech early adopters",
        markets: "US national",
        exclusions: "Existing Verizon subscribers (CRM)",
      },
      activation: {
        channels: "Broadcast, CTV, programmatic, social",
        pmp: "Yes",
        dsp: "DV360 + Amazon DSP",
        sponsorshipNeeds: "In-game branding, halftime features, broadcast integration",
        momentsTriggers: "Touchdown, red zone, primetime kickoff",
      },
      measurement: {
        attribution: "Brand lift + sponsorship recall study",
        liftStudy: "Required — network quality perception",
        reporting: "Bi-weekly sponsorship reporting",
        enrichment: "NFL team affinity overlays",
      },
      recommendedProducts: [
        "Sponsorship & Broadcast",
        "Audiences / Fan Graph",
        "Managed Service",
        "Measurement / Insights",
      ],
    },
    workstreams: [],
    risks: [],
    proposalDraft: {
      executiveSummary:
        "Verizon sought an integrated NFL 5G showcase combining broadcast sponsorship with digital amplification. Proposal included managed service and Fan Graph targeting.",
      strategicRecommendation:
        "Leverage broadcast equity with 5G messaging during primetime and red zone moments.",
      audienceStrategy: "NFL fans 25-54 with tech early adopter segments.",
      recommendedProducts:
        "Sponsorship & Broadcast, Audiences / Fan Graph, Managed Service, Measurement / Insights",
      activationPlan: "Sep–Feb broadcast + digital package with primetime moment triggers.",
      measurementPlan: "Brand lift for network quality perception + sponsorship recall.",
      openQuestions: "Lost on broadcast package pricing to competitor.",
      internalCaveats: "Strong proposal — revisit for 2025 renewal cycle.",
    },
    currentStage: "Complete",
    nextAction: "Archive — lost to competitor",
  },
  {
    id: "hist-gatorade-ncaa-2024",
    createdAt: "2024-02-14T09:00:00Z",
    updatedAt: "2024-03-28T15:00:00Z",
    completedAt: "2024-03-28T15:00:00Z",
    outcome: "Won",
    tags: ["NCAA", "college football", "brand awareness", "Fan Graph", "managed service"],
    summary:
      "Gatorade NCAA March Madness and CFB brand awareness with Fan Graph alumni segments. Won with managed service delivery.",
    advertiser: "Gatorade",
    agency: "TBWA",
    campaign: "Fuel the Madness",
    owner: "Marcus Webb",
    deadline: "2024-03-01",
    status: "Complete",
    complexity: "Medium",
    riskLevel: "Low",
    percentComplete: 100,
    intakeNotes:
      "Gatorade March Madness + CFB awareness. College sports fans, alumni targeting, $2.8M budget. Brand lift and hydration category growth.",
    solutionBrief: {
      opportunity: {
        advertiser: "Gatorade",
        agency: "TBWA",
        campaign: "Fuel the Madness",
        owner: "Marcus Webb",
      },
      timing: { flight: "Mar 15 – Dec 31, 2024", deadline: "2024-03-01" },
      business: {
        objective: "Drive hydration brand awareness during college sports season",
        kpi: "Reach, brand lift, category share",
        budget: "$2.8M",
      },
      audience: {
        target: "College sports fans, alumni, athletes 18-34",
        markets: "US — tournament and CFB priority markets",
        exclusions: "Competitive sports drink purchasers",
      },
      activation: {
        channels: "Programmatic video, CTV, display, social",
        pmp: "Yes",
        dsp: "DV360",
        sponsorshipNeeds: "Tournament moment integration",
        momentsTriggers: "Buzzer beater, upset alert, rivalry games",
      },
      measurement: {
        attribution: "Multi-touch attribution",
        liftStudy: "Required — brand lift study",
        reporting: "Tournament + CFB season reporting",
        enrichment: "Alumni affiliation overlays",
      },
      recommendedProducts: [
        "Curated Deals",
        "Audiences / Fan Graph",
        "Moments",
        "Managed Service",
        "Measurement / Insights",
      ],
    },
    workstreams: [],
    risks: [],
    proposalDraft: {
      executiveSummary:
        "Gatorade needed college sports awareness spanning March Madness through CFB. Managed service with Fan Graph alumni targeting won the business.",
      strategicRecommendation:
        "Activate around tournament upsets and rivalry games with hydration messaging.",
      audienceStrategy: "College sports fans with alumni and athlete affinity segments.",
      recommendedProducts:
        "Curated Deals, Audiences / Fan Graph, Moments, Managed Service, Measurement / Insights",
      activationPlan: "Mar–Dec flight with tournament and CFB moment triggers.",
      measurementPlan: "Brand lift study with alumni segment enrichment.",
      openQuestions: "None.",
      internalCaveats: "Delivered successfully — reference for future CFB RFPs.",
    },
    currentStage: "Complete",
    nextAction: "Archive — won and delivered",
  },
  {
    id: "hist-espn-streaming-2024",
    createdAt: "2024-08-01T10:00:00Z",
    updatedAt: "2024-08-15T09:00:00Z",
    completedAt: "2024-08-15T09:00:00Z",
    outcome: "No Bid",
    tags: ["streaming", "ESPN", "acquisition", "CTV", "no bid"],
    summary:
      "ESPN+ streaming subscriber acquisition with CTV and sports fan targeting. No bid — budget below minimum deal threshold.",
    advertiser: "ESPN",
    agency: "Internal",
    campaign: "ESPN+ Fall Subscriber Push",
    owner: "James Okonkwo",
    deadline: "2024-08-10",
    status: "Complete",
    complexity: "Low",
    riskLevel: "Low",
    percentComplete: 100,
    intakeNotes:
      "ESPN+ fall subscriber acquisition. CTV focus, sports fan audiences, $400K budget. Free trial sign-ups and app installs.",
    solutionBrief: {
      opportunity: {
        advertiser: "ESPN",
        agency: "Internal",
        campaign: "ESPN+ Fall Subscriber Push",
        owner: "James Okonkwo",
      },
      timing: { flight: "Sep 1 – Nov 30, 2024", deadline: "2024-08-10" },
      business: {
        objective: "Drive ESPN+ free trial sign-ups during fall sports season",
        kpi: "Trial sign-ups, app installs, CPA",
        budget: "$400K",
      },
      audience: {
        target: "Sports fans, cord-cutters, streaming intenders 25-44",
        markets: "US",
        exclusions: "Existing ESPN+ subscribers",
      },
      activation: {
        channels: "CTV, programmatic video",
        pmp: "Preferred",
        dsp: "DV360",
        sponsorshipNeeds: "None",
        momentsTriggers: "Game start, halftime",
      },
      measurement: {
        attribution: "Last-click CPA tracking",
        liftStudy: "Not requested",
        reporting: "Weekly CPA and reach reporting",
        enrichment: "Sports league affinity",
      },
      recommendedProducts: ["Curated Deals", "Audiences / Fan Graph"],
    },
    workstreams: [],
    risks: [],
    proposalDraft: {
      executiveSummary:
        "ESPN+ sought fall subscriber acquisition via CTV. Budget of $400K fell below minimum deal threshold for managed PMP packaging.",
      strategicRecommendation:
        "Self-serve Curated Deals recommended if budget increases to $750K+.",
      audienceStrategy: "Sports fans and cord-cutters via Fan Graph.",
      recommendedProducts: "Curated Deals, Audiences / Fan Graph",
      activationPlan: "CTV-focused flight with game start triggers.",
      measurementPlan: "Last-click CPA tracking.",
      openQuestions: "Client declined budget increase.",
      internalCaveats: "No bid — below minimum threshold. Revisit if budget increases.",
    },
    currentStage: "Complete",
    nextAction: "Archive — no bid",
  },
  {
    id: "hist-budlight-nhl-2023",
    createdAt: "2023-09-01T08:00:00Z",
    updatedAt: "2023-10-20T17:00:00Z",
    completedAt: "2023-10-20T17:00:00Z",
    outcome: "Won",
    tags: ["NHL", "hockey", "brand lift", "PMP", "moments"],
    summary:
      "Bud Light NHL season awareness with hockey fan segments and goal moment triggers. Won with brand lift study and PMP on TTD.",
    advertiser: "Bud Light",
    agency: "DDB",
    campaign: "Hockey Night Refresh",
    owner: "Priya Sharma",
    deadline: "2023-09-15",
    status: "Complete",
    complexity: "Medium",
    riskLevel: "Low",
    percentComplete: 100,
    intakeNotes:
      "Bud Light NHL season refresh. Hockey fans 21+, brand lift study, goal and power play moments. $1.5M budget on TTD PMP.",
    solutionBrief: {
      opportunity: {
        advertiser: "Bud Light",
        agency: "DDB",
        campaign: "Hockey Night Refresh",
        owner: "Priya Sharma",
      },
      timing: { flight: "Oct 10, 2023 – Apr 15, 2024", deadline: "2023-09-15" },
      business: {
        objective: "Refresh Bud Light brand association with NHL hockey culture",
        kpi: "Reach, brand lift (+3pts), engagement",
        budget: "$1.5M",
      },
      audience: {
        target: "NHL fans 21+, hockey enthusiasts, beer category intenders",
        markets: "US + Canada — NHL market cities",
        exclusions: "Under 21, competitive beer purchasers",
      },
      activation: {
        channels: "Programmatic video, CTV, display",
        pmp: "Yes — NHL PMP on TTD",
        dsp: "The Trade Desk",
        sponsorshipNeeds: "None",
        momentsTriggers: "Goal scored, power play start, period break",
      },
      measurement: {
        attribution: "Multi-touch attribution",
        liftStudy: "Required — brand lift study",
        reporting: "Monthly dashboards + postseason readout",
        enrichment: "NHL team affinity segments",
      },
      recommendedProducts: [
        "Curated Deals",
        "Audiences / Fan Graph",
        "Moments",
        "Measurement / Insights",
      ],
    },
    workstreams: [],
    risks: [],
    proposalDraft: {
      executiveSummary:
        "Bud Light sought NHL season brand refresh with measurable impact. Won with hockey Fan Graph segments and goal moment activation.",
      strategicRecommendation:
        "Activate around goal and power play moments with hockey culture creative.",
      audienceStrategy: "NHL fans 21+ with team affinity weighting in market cities.",
      recommendedProducts:
        "Curated Deals, Audiences / Fan Graph, Moments, Measurement / Insights",
      activationPlan: "Oct–Apr flight on TTD PMP with goal moment triggers.",
      measurementPlan: "Brand lift study (+3pt target) with team affinity enrichment.",
      openQuestions: "None.",
      internalCaveats: "Strong reference case for NHL and beer category RFPs.",
    },
    currentStage: "Complete",
    nextAction: "Archive — won and delivered",
  },
];
